config/routes.rb
Depot::Application.routes.draw do
  resources :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :title, :description, :price

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  private
  def product_params
    params.require(:product).permit(:title, :description, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Depot
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag "application", :medial => "all", 'data-turbolinks-track' => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

    %body{:class => "#{controller.controller_name}"}
      %div{:class => "navbar navbar-default navbar-fixed-top"}
        %div{:class => "container"}
          %div{:class => "navbar-header"}
            %button{:type => "button", :class => "navbar-toggle collapsed", "data-toggle" => "collapse", "data-target" => ".navbar-collapse"}
              %span{:class => "icon-bar"}
              %span{:class => "icon-bar"}
              %span{:class => "icon-bar"}
            %a{:class => "navbar-brand", :href => "#"} Depot Web Application 
          %div{:class => "navbar-collapse collapse", :style=> "height: 1px;"}
            %ul{:class => "nav navbar-nav"}
              %li
                = link_to 'List Products', products_path
              %li
                = link_to 'New Product', new_product_path
      %div{:class => "container app_content"}
        = yield

app/views/products/_form.html.haml
= render(:partial => 'shared/errors', :locals => {:object => @product})
= form_for(@product, :class => "form-horizontal", :role => "form") do |f|
  %div{:class => "form-group"}
    %label Title
    = f.text_field :title, :placeholder => "Title", :class => "form-control"
  %div{:class => "form-group"}
    %label Description
    = f.text_area :description, :placeholder => "Description", :class => "form-control", :rows => 10
  %div{:class => "form-group"}
    %label Price
    = f.text_field :price, :placeholder => "Price", :class => "form-control"
  = f.submit

app/views/products/edit.html.haml
= render('products/form')

app/views/products/index.html.haml
%h1 Products Listing

%table{:class => "table table-condensed table-striped"}
  %thead
    %tr
      %th Title
      %th Description
      %th Price
      %th Links
  %tbody
    - @products.each do |product|
      %tr
        %td= product.title
        %td= raw product.description
        %td= number_to_currency product.price, :precision => 2
        %td= link_to('Show', product_path(product))

%div
  = link_to('New Product', new_product_path)

app/views/products/new.html.haml
%h1 New Product

= render('products/form')

app/views/products/show.html.haml
%label Title:
%p= @product.title
%p
%label Description: 
%p= raw @product.description
%p
%label Price:
%p= number_to_currency @product.price, :precision => 2

app/views/shared/_errors.html.haml
- if object.errors.full_messages.size > 0
  %div{:class => "alert alert-danger"}
    %ul
      - object.errors.full_messages.each do |message|
        %li= message